---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Find bastion instances
      ec2_instance_facts:
        region: "{{ aws_region }}"
        filters: 
          "tag:Role": bastion
      register: found

    - ec2:
        key_name: "{{ aws_app_instance_pem }}"
        group: bastion
        region: "{{ aws_region }}"
        instance_type: t2.micro
        image: ami-d874e0a0
        wait: yes
        wait_timeout: 600
        count: 1
        instance_tags:
           Role: bastion
           Name: Bastion server
        monitoring: yes
        vpc_subnet_id: subnet-1603856f
        assign_public_ip: yes
      when: 
        - found is defined
        - found.instances|length < 1
          

    #- name: get bastion host
    #  debug:
    #    msg: "{{ found }}"

- hosts: tag_Role_bastion
  user: ec2-user
  tasks:
    - name: Add .ssh directory
      file: 
        path: /home/ec2-user/.ssh
        state: directory
        owner: ec2-user
        mode: 0700

    - name: Push authorized_hosts for ec2-user
      copy:
        src: files/{{ env }}_authorized_keys
        dest: /home/ec2-user/.ssh/authorized_keys
        mode: 0600
